name: Open GitHub issue (by tr325)
author: Tom Renner
description: "Opens a GitHub issue -- a learning excercise from tr325"
inputs:
  token:
    description: "Github Token"
    required: true
  title:
    description: "Issue title"
    required: true
  body:
    description: "Issue body"
  assignees:
    description: "Issue assignees"
outputs:
  issue:
    description: "The issue object as a json string"
runs:
  using: "node12"
  main: "dist/index.js"
# For branding in the GitHub Marketplace
branding:
  icon: "alert-octagon"
  color: "purple"
